server:
  port: 3002
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.111.1:8848
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format: true
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
  datasource:
    url: jdbc:mysql://localhost:3306/my-blog?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: hyxiao
logging:
  level:
    org.springframework.cloud.openfeign: debug
    org.springframework.cloud.sleuth: debug