server:
  port: 3001
spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format: true
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
  datasource:
    url: jdbc:mysql://localhost:3306/my-blog?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: hyxiao
  redis:
    host: localhost
    port: 6379
    database: 0
logging:
  level:
    org.springframework.cloud.openfeign: debug
    org.springframework.cloud.sleuth: debug