server:
  port: 3000
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1  # tomcat默认大小2M，超过2M的文件不会被捕获，需要调整此处大小为100MB或者-1即可
spring:
  application:
    name: gateway
  profiles:
    active: dev
  cloud:
    loadbalancer:
      nacos:
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: true       # 开启动态路由，从注册中心根据微服务名称获得目标节点
      routes: # 配置路由规则（数组）
        - id: blogRoute # 每一项路由都有一个唯一id
          uri: lb://blog-service        # lb 代表负载均衡，会动态寻址
          predicates: # 匹配断言，符合条件的则放行（可以精确到具体的接口名）
            - Path=/api/blog/**    # 请求的时候，则会请求到用户服务中的匹配u路由
        - id: commentRoute # 每一项路由都有一个唯一id
          uri: lb://comment-service        # lb 代表负载均衡，会动态寻址
          predicates: # 匹配断言，符合条件的则放行（可以精确到具体的接口名）
            - Path=/api/comment/**    # 请求的时候，则会请求到用户服务中的匹配u路由
      globalcors:
        cors-configurations:
          '[/**]': # 映射路径
            allowedOriginPatterns: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
            allowCredentials: true

# 日志级别
logging:
  level:
    root: info

blackIP:
  continueCounts: ${counts:5}   # ip连续请求的次数
  timeInterval: ${interval:20}  # ip判断的时间间隔，单位：秒
  limitTimes: ${times:30}       # 限制的时间，单位：秒